name: "playwright"
description: "run e2e tests"

inputs:
  project:
    description: "project name"
    required: false
    type: string
    default: "web"
  workdir:
    description: "working directory"
    type: string
    default: "./e2e-tests"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: install deps
      run: npm ci
      shell: bash
      working-directory: ${{ inputs.workdir }}
    - name: install playwright browsers
      run: npx playwright install --with-deps
      shell: bash
      working-directory: ${{ inputs.workdir }}
    - name: Run Playwright tests
      run: npx playwright test --project=${{ inputs.project }} --trace on
      shell: bash
      working-directory: ${{ inputs.workdir }}