name: "playwright"
description: "run e2e tests"

inputs:
  project:
    description: "project name"
    required: false
    type: string
    default: "web"
  workdir:
    description: "working directory"
    type: string
    default: "./e2e-tests"

runs:
  using: "composite"
  steps:
    - name: Ensure Docker network exists
      run: docker network inspect playwright || docker network create playwright 
      shell: bash
      
    - name: Stop and remove existing container
      run: |
        docker stop playwright || true
        docker rm playwright || true
      shell: bash
      
    - name: build playwright docker container 
      run: docker build . -f Dockerfile-playwright -t playwright
      shell: bash
      working-directory: ${{ inputs.workdir }}

    - name: run playwright docker container
      run: docker run --network=playwright --name playwright-tests playwright
      shell: bash
      working-directory: ${{ inputs.workdir }}