name: "backend"
description: "build backend docker image for e2e tests"

inputs:
  workdir:
    description: "working directory"
    type: string
    default: "./be"

runs:
  using: "composite"
  steps:
    - name: Ensure Docker network exists
      run: docker network inspect playwright || docker network create playwright 
      shell: bash 
    - name: Stop and remove existing container
      run: |
        docker stop backend || true
        docker rm backend || true
      shell: bash

    - name: build backend docker image
      run: docker build . -t backend
      working-directory: ${{ inputs.workdir }}
      shell: bash

    - name: run backend docker container
      run: docker run --network=playwright --name backend -p 8080:8080 -d backend
      working-directory: ${{ inputs.workdir }}
      shell: bash    