name: "frontend"
description: "build frintend docker image for e2e tests"

inputs:
  project:
    description: "project name"
    required: false
    type: string
    default: "web"
  workdir:
    description: "working directory"
    type: string
    default: "./fe"

runs:
  using: "composite"
  steps:
    - name: Ensure Docker network exists
      run: docker network inspect playwright || docker network create playwright  
    - name: Stop and remove existing container
      run: |
        docker stop frontend || true
        docker rm frontend || true
        
    - name: build frontend docker image
      run: docker build . -f Dockerfile-front-end -t frontend
      working-directory: ${{ inputs.workdir }}

    - name: run frontend docker container
      run: docker run --network=playwright --name frontend -p 3000:3000 -d frontend
      working-directory: ${{ inputs.workdir }}    