name: main
run-name: playwright
on: [workflow_dispatch, push]
jobs:
    pages:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: run playwright tests
          uses: ./.github/workflows/playwright
          with:
            project: web
            dir: ./e2e-tests
          # uses: ./.github/workflows/actions/playwright
          # with:
          #   project: chromium
          #   workdir: ./e2e-tests    

