name: main
run-name: ${{github.actor}}
on: [workflow_dispatch, push]
jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: build docker image
          run: docker build . -t my-app
          working-directory: ./fe
        - name: run docker container
          run: docker run my-app
          working-directory: ./fe
        - name: checkout
          uses: actions/checkout@v4  
        - uses: ./.github/workflows/playwright.yml
          with:
            name: chromium
            workdir: ./e2e-tests        

        
  
