name: main
run-name: ${{github.actor}}
on: [workflow_dispatch, push]
jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: create docker network
          run: docker network create playwright 
        - name: build frontend docker image
          # uses: actions/checkout@v4
          uses: ./.github/workflows/actions/frontend/frontend.yml
          with:
            project: web
            workdir: ./fe
    # playwright:
    #   needs: frontend
    #   uses: ./.github/workflows/playwright.yml
    #   with:
    #     name: chromium
    #     workdir: ./e2e-tests
        - name: echoing
          run: docker ps && docker network ls
        - name: create bash-test docker
          run: docker build . -t bash-test  
          working-directory: ./fe
        - name: run bash container
          run: docker run --network=playwright bash-test 
          working-directory: ./fe  


        
  
