name: main
run-name: ${{github.actor}}
on: [workflow_dispatch, push]
jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: build docker image
          run: docker build . -f Dockerfile-front-end -t frontend
          working-directory: ./fe
        - name: run docker container
          run: docker run -p 3000:3000 -d frontend --name frontend
          working-directory: ./fe
    # playwright:
    #   needs: frontend
    #   uses: ./.github/workflows/playwright.yml
    #   with:
    #     name: chromium
    #     workdir: ./e2e-tests
        - name: echoing
          run: docker network ls
        - name: echoing2
          run: curl http://0.0.0.0:3000


        
  
