name: main
run-name: ${{github.actor}}
on: [workflow_dispatch, push]
jobs:
    frontend:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: build docker image
          run: docker build . -f Dockerfile-front-end -t my-app
          working-directory: ./fe
        - name: run docker container
          run: docker run -d  my-app
          working-directory: ./fe
    # playwright:
    #   needs: frontend
    #   uses: ./.github/workflows/playwright.yml
    #   with:
    #     name: chromium
    #     workdir: ./e2e-tests
        - name: echoing
          run: curl "http://127.0.0.1:3000"


        
  
