name: playwright

on:
  workflow_call:
    inputs:
      project:
        description: "project name"
        required: false
        type: string
        default: "chromium"
      tests-dir:
        description: "tests directory"
        type: string
        default: "./e2e-tests"
      gh-page-branch:
        description: "GitHub page default branch"
        type: string
        default: "allure-report"
      allure-results-dir:
        description: "allure results directory"
        type: string
        default: "allure-results"

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/playwright:v1.51.0-noble
      options: --user 1001
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.tests-dir }}

      - name: Run Playwright tests
        run: npx playwright test --project ${{ inputs.project }}
        working-directory: ${{ inputs.tests-dir }}

      - name: Load test report history
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: ${{ inputs.gh-page-branch }}
          path: ${{ inputs.gh-page-branch }}

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        continue-on-error: true
        with:
          gh_pages: ${{ inputs.gh-page-branch }}
          allure_history: allure-history
          allure_results: ${{ inputs.tests-dir }}/${{ inputs.allure-results-dir }}

      - name: Upload Allure report
        uses: peaceiris/actions-gh-pages@v4
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history
          publish_branch: ${{ inputs.gh-page-branch }}