name: playwright

on:
  workflow_call:
    inputs:
      name:
        description: "progect name"
        required: true
        type: string
      workdir:
        description: "working directory"
        type: string
        default: "/apps/e2e-tests"    

jobs:
  playwright:
    name: playwright tests
    runs-on: ubuntu-latest
    services:
      playwright:
        image: mcr.microsoft.com/playwright:v1.51.1-noble
        options: --network=playwright
        ports:
          - 3000:3000
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: install deps
          run: npm install
          working-directory: ${{ inputs.workdir }}
        - name: run tests
          run: npx playwright test --project=${{ inputs.name }} -- trace on
          working-directory: ${{ inputs.workdir }}    
   