name: Reusable workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Input to the reusable workflow'
        required: true
        type: string
      surname:
        required: true
        type: string
    outputs:
      # Map the workflow output(s) to job output(s)
      reusable_output:
        description: 'Output from the reusable workflow'
        value: ${{ jobs.reusable-workflow-job.outputs.job_output }}

defaults:
  run:
    shell: bash

jobs:
  reusable-workflow-job:
    runs-on: ubuntu-20.04
    # Map the job output(s) to step output(s)
    outputs:
      job_output: ${{ steps.process-step.outputs.step_output }}
    steps:
      - name: Process reusable input
        id: process-step
        env:
          HELLO_WORLD_SECRET: ${{ secrets.HELLO_WORLD_SECRET }}
        run: |
          echo "reusable_input=${{ inputs.name }}"
          echo "step_output=${{ inputs.surname }}_processed" >> $GITHUB_OUTPUT
      - name: Process file
        run: |
          echo "Processing file: ${{ inputs.name }}"
          echo "file processed" >> ${{ inputs.surname }}
