name: Reusable Workflow

on:
  workflow_call:
    inputs:
      name:
        description: "Input name"
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print input
        run: echo "Hello, ${{ inputs.name }}"