name: Frontend Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-frontend:
    runs-on: [self-hosted, macOS]

    steps:
      # Checkout the repository
      - name: run simple code
        run: echo "self hosted"
