name: e2e tests
run-name: ${{github.actor}}
on: [push, workflow_dispatch]
jobs:
    fe:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node-version: '18'
        - name: install front-end deps, and build and start
          run: npm i && npm run build
          working-directory: ./fe
        - name: install test, browsers and run tests
          run: npm i && npx playwright install --with-deps && npx playwright test
          working-directory: ./e2e-tests


