name: Frontend Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-frontend:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Run the frontend in a container
      - name: Run frontend in Docker container
        run: |
          docker build . -f Dockerfile-front-end -t frontend-app 
          docker run -d -p 3000:3000 --name frontend-container frontend-app
        env:
          CI: true
        working-directory: ./fe
      # Wait for the frontend to start
      - name: Wait for frontend to start
        run: |
          sleep 10

      # Make a curl request to the frontend start page
      - name: Test frontend start page
        run: |
          curl -f http://localhost:3000 || exit 1

      # Cleanup Docker container
      - name: Cleanup Docker container
        if: always()
        run: |
          docker stop frontend-container
          docker rm frontend-container