name: e2e tests
run-name: ${{github.actor}}
on: [workflow_dispatch, push]
jobs:
    fe:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: build docker image
          run: docker build . -t my-app
          working-directory: ./fe
        - name: run docker container
          run: docker run my-app
          working-directory: ./fe
        - name: install test, browsers and run tests
          run: npm i && npx playwright install --with-deps && npx playwright test 
          working-directory: ./e2e-tests
    work:
      needs: [fe]
      uses: ./.github/workflows/reusable-workflow.yml
      with:
        name: rodion
        
  
