name: e2e tests
run-name: Rodion
on: [push]
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: test
            run: echo test
    fe:
      runs-on: ubuntu-latest
      steps:
        - name: lsing
          run: ls
        - name: checkout
          uses: actions/checkout@v4
        - name: lsing
          run: ls


