name: e2e tests
run-name: Rodion
on: [push]
jobs:
    fe:
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: switch to front-end
          run: ls
          working-directory: ./fe
#        - name: install node
#          uses: actions/setup-node@v3
#          with:
#            node-version: '18'
#        - name: install deps
#          run: npm i
#        - name: build fe app
#          run: npm run build



